### ISSUE TITLE
when will the Controllable Image Synthesis Code be released?

### ISSUE THREAD

**Issue by Anonym0u3** [modelscope/scepter#1]
Thank you for your outstanding work, may i ask when will the Controllable Image Synthesis Code be released?

**Comment by maochaojie** [comment]
The models are currently available on ModelScope including 72 style models and 2 conditional generative models., along with an interactive demo. You can access it now to experience it for yourself. We plan to release the code implementation for controlled generation next Monday and will also provide a tool for training and inference with this release.

**Comment by maochaojie** [comment]
The link is https://modelscope.cn/models/damo/scepter_scedit/summary and https://www.modelscope.cn/studios/damo/scepter_studio/summary

**Comment by Anonym0u3** [comment]
> The models are currently available on ModelScope including 72 style models and 2 conditional generative models, along with an interactive demo. You can access it now to experience it for yourself. We plan to release controllable image synthesis code next Monday(January 15th) and will also provide a tool for training and inference with this release.

谢谢您的回复，我想再问一下论文中图4的c Cascade Dense Convolution的网络框架是什么，我看文中没有具体的框架，还是说针对不同的conditions有不同的网络框架

**Comment by jiangzeyinzi** [comment]
We have released the code for controllable image generation along with some of the models, thank you for your attention.
