### ISSUE TITLE
怎么指定可以跑自己准备的数据集，而非ms数据集

### ISSUE THREAD

**Issue by wangweilovelife** [modelscope/scepter#10]

**Comment by jiangzeyinzi** [comment]
SCEPTER当前支持MS、CSV、TXT格式的输入，同时支持本地、HTTP、MS、OSS等存储格式，可以参考readme中`Data Text Format`中的`xxx_datatxt.yaml`样例使用自己准备的数据集进行训练与测试。此外SCEPTER是一个完备的训练、推理框架，可以自行register自定义的Dataset以实现需求。
