### ISSUE TITLE
能否用diffusers加载SCEdit的权重？

### ISSUE THREAD

**Issue by YoucanBaby** [modelscope/scepter#19]
作者大佬您好，能否用diffusers加载SCEdit的权重？

**Comment by YoucanBaby** [comment]
此外，huggingFace上没有controlNet_SDXL

**Comment by jiangzeyinzi** [comment]
感谢您关注我们的工作！当前该工作暂时还没有接入到diffusers代码库中，您可以使用scepter或自主开发实现需要的功能。另外，SDXL-based Controllable Model，您可以先从 Modelscope (https://modelscope.cn/models/iic/scepter_scedit/summary)中进行获取，后续我们会同步到huggingface上。

**Comment by YoucanBaby** [comment]
> 感谢您关注我们的工作！当前该工作暂时还没有接入到diffusers代码库中，您可以使用scepter或自主开发实现需要的功能。另外，SDXL-based Controllable Model，您可以先从 Modelscope (https://modelscope.cn/models/iic/scepter_scedit/summary) 中进行获取，后续我们会同步到huggingface上。

好的，谢谢作者大大的回复。期待diffusers版本的SCEdit。
