### ISSUE TITLE
How to training with LAE-Gen model

### ISSUE THREAD

**Issue by Noctifier** [modelscope/scepter#27]
Thank you for your outstanding work, may i ask when will the LAE-Gen Code and training guidance be released?

**Comment by LouieStark** [comment]
Sorry for late reply. Considering the copyright issue of training data of LAR-Gen, we won’t be able to open-source the standard training configuration file for reproduction. However, we will soon provide a demo version of the training configuration.

**Comment by Noctifier** [comment]
Thanks for your reply. Actually I want to train the model with our own dataset.
