### ISSUE TITLE
First stage training config (Autoencoder)

### ISSUE THREAD

**Issue by sahilqure** [modelscope/scepter#30]
I understand that full finetuning sdxl without the first stage on natural images works precisely but for images of other domains like (CT, MRI, and stuff), first-stage training of autoencoder is required.

**Comment by jiangzeyinzi** [comment]
In the generic diffusion-based text-to-image generation model, the VAE is typically trained independently with the addition of reconstruction loss and GAN loss. Currently, we do not have the corresponding implementation or configuration files, and contributions are welcome.
