### ISSUE TITLE
how can train multi conditional inputs?

### ISSUE THREAD

**Issue by nguyendung1612** [modelscope/scepter#31]
Thank you for your outstanding work, may i ask how can train with multi conditional inputs like Multi1 and Multi2?

**Comment by jiangzeyinzi** [comment]
Do you mean the multi-condition generation task in SCEdit? As described in the paper, we haven't trained on multi-condition scenarios, only utilizing jointly the conditions that have been trained independently. Unfortunately, our Gradio interface does not support this feature at the moment.
