### ISSUE TITLE
hf demo is broken

### ISSUE THREAD

**Issue by yisol** [modelscope/scepter#32]
hello,
I think hf demo link is broken https://huggingface.co/spaces/modelscope/scepter_studio
Can you check this out please?

**Comment by maochaojie** [comment]
thank your feedback, we will fix it very soon

**Comment by jiangzeyinzi** [comment]
We have fixed and it is now available for use. 
Additionally, you can also use our demo on the Modelscope platform: https://www.modelscope.cn/studios/iic/scepter_studio/summary
