### ISSUE TITLE
COCO Dataset Configuration for Text-to-Image 

### ISSUE THREAD

**Issue by qsunyuan** [modelscope/scepter#33]
I would like to extend my sincere appreciation for your extensive work on diffusion models based tuning. 

I am reaching out to inquire if you have any specific configuration files or guidance available for using the COCO dataset with Text-to-image generation (SCEdit paper).

**Comment by jiangzeyinzi** [comment]
Thank you for your interest in our work. The training process documentation for SCEdit can be found at [text-to-image-generation](https://github.com/modelscope/scepter/blob/main/docs/en/tutorials/train.md#text-to-image-generation). For information on using your custom dataset, please refer to the `Data Text Format` section of the dataset construction part in the yaml file. The settings for the hyperparameters are described in detail in Table 4 of the paper's appendix.
