### ISSUE TITLE
Any tutorials on edit tuner?

### ISSUE THREAD

**Issue by HoiM** [modelscope/scepter#37]
Which yaml file and training code correspond to edit tuner training?

**Comment by hanzhn** [comment]
If using python, you can try the launch code at https://github.com/modelscope/scepter/blob/cbbef4a2da5b66fc33b9f8ece7f2fb4aac9d6e3c/tests/tools/test_train.py#L220. We provide edit tuner training settings in this [yaml](https://github.com/modelscope/scepter/blob/main/scepter/methods/edit/edit_512_lora.yaml). Check [StyleBooth page](https://github.com/modelscope/scepter/blob/main/docs/en/tasks/stylebooth.md#styletuner-and-de-styletuner) for more information.

Or you want to try on gradio, please try [scepter studio](https://github.com/modelscope/scepter/tree/main?tab=readme-ov-file#%EF%B8%8F-scepter-studio) for easy managing your training data, tuning and inference.
