### ISSUE TITLE
About SCEdit-Control on PixArt

### ISSUE THREAD

**Issue by carvychen** [modelscope/scepter#40]
Thank you for your hard work in supporting the PixArt model in Scepter. I was wondering if it supports the training of SCEdit-Control on PixArt? How can I set up the correct config YAML file?

**Comment by jiangzeyinzi** [comment]
SCEdit is designed based on the U-Net architecture, making it incompatible with the DiT architecture used in PixArt. One possible approach to address this is by using a base model like U-ViT (which includes skip connections) for adaptation. 
For conditional control on DiT, you can refer to the method described in the original PixArt paper. 
Additionally, we are actively developing more advanced conditional control techniques on DiT.
