### ISSUE TITLE
SCEdit Controllable SC-Tuner semantic segmentation checkpoint, training code and configuration

### ISSUE THREAD

**Issue by XIRZC** [modelscope/scepter#8]
Thank you for your outstanding work and contributions!

I've reviewed the released paper, which includes impressive results on semantic segmentation map-based conditional generation. However, upon visiting the Scepter modelscope link (https://modelscope.cn/models/iic/scepter_scedit/files), I couldn't find any models specifically focused on semantic segmentation map-based conditional generation.

I'm curious to know why this particular model hasn't been released yet. Additionally, I'm wondering if there are plans to release the code and configuration for training semantic segmentation map-based conditional generation models. Your insights on this matter would be greatly appreciated.

**Comment by jiangzeyinzi** [comment]
SCEdit is currently integrated into the SCEPTER framework, and to maintain the simplicity of the framework, we have not introduced a heavy code for segmentation models. Segmentation-based control can be easily trained, and one can refer to other conditional methods for the data organization and training.

**Comment by XIRZC** [comment]
Thanks.
